apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: tpcds-benchmark-data-generation-1t
  namespace: spark
spec:
  type: Scala
  pythonVersion: "3"
  mode: cluster
  image: ghcr.io/abin-tiger/spark-tpc-ds:main
  imagePullPolicy: Always
  mainClass: com.amazonaws.eks.tpcds.DataGeneration
  mainApplicationFile: local:///opt/spark/examples/jars/eks-spark-benchmark-assembly-1.0.jar
  arguments:
  # TPC-DS data localtion
    - "s3a://my_s3_bucket/TPCDS-TEST-1T"
  # Path to kit in the docker image
    - "/opt/tpcds-kit/tools"
  # Data Format
    - "parquet"
  # Scale factor (in GB)
    - "1000"
  # Generate data num partitions
    - "200"
  # Create the partitioned fact tables
    - "false"
  # Shuffle to get partitions coalesced into single files.
    - "false"
  # Logging set to WARN
    - "true"
  hadoopConf:
    # IRSA configuration
    "fs.s3a.aws.credentials.provider": "com.amazonaws.auth.InstanceProfileCredentialsProvider"
    "fs.s3a.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem"
  sparkConf:
    "spark.hadoop.mapreduce.outputcommitter.factory.scheme.s3a": "org.apache.hadoop.fs.s3a.commit.S3ACommitterFactory"
    "spark.kubernetes.executor.podNamePrefix": "tpc-ds"
    "spark.hadoop.fs.s3a.connection.timeout": "1200000"
    "spark.hadoop.fs.s3a.path.style.access": "true"
    "spark.hadoop.fs.s3a.connection.maximum": "200"
    "spark.hadoop.fs.s3a.fast.upload": "true"
    "spark.hadoop.fs.s3a.readahead.range": "256K"
    "spark.hadoop.fs.s3a.input.fadvise": "random"
    "spark.sql.execution.arrow.pyspark.enabled": "true"
    "spark.eventLog.enabled": "true"
    "spark.eventLog.dir": "s3a://my_s3_bucket/spark-event-logs/"
  sparkVersion: "3.1.2"
  driver:
    cores: 7
    memory: "57g"
    memoryOverhead: "2g"
    serviceAccount: spark-driver
  executor:
    cores: 7
    memory: "57g"
    memoryOverhead: "2g"
    serviceAccount: spark-driver
  dynamicAllocation:
    enabled: true
    initialExecutors: 3
    minExecutors: 1
    maxExecutors: 10